name: ci

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
      # Here I used a ready-made official Dockerhub solution for image caching, which speeds up the compilation of images many times, there are many such solutions for caching
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile #
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.USERNAME }}/easycache:latest
          cache-from: type=registry,ref=${{ secrets.USERNAME }}/easycache:buildcache
          cache-to: type=registry,ref=${{ secrets.USERNAME }}/easycache:buildcache,mode=max
